#if !canImport(ObjectiveC)
import XCTest

extension ConcurrentDictionaryLockTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConcurrentDictionaryLockTests = [
        ("test_subscriptGet_onSequentialEnvironment_fromDictionaryContainingValueForKey_mustReturnValue", test_subscriptGet_onSequentialEnvironment_fromDictionaryContainingValueForKey_mustReturnValue),
        ("test_subscriptGet_onSequentialEnvironment_fromEmptyDictionary_mustReturnNil", test_subscriptGet_onSequentialEnvironment_fromEmptyDictionary_mustReturnNil),
        ("test_subscriptSet_onSequentialEnvironment_fromEmptyDictionary_mustInsertKeyValue", test_subscriptSet_onSequentialEnvironment_fromEmptyDictionary_mustInsertKeyValue),
        ("test_subscriptSetMultipleTimes_onConcurrentEnvironment_mustInsertAllKeyValuePairs", test_subscriptSetMultipleTimes_onConcurrentEnvironment_mustInsertAllKeyValuePairs),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ConcurrentDictionaryLockTests.__allTests__ConcurrentDictionaryLockTests),
    ]
}
#endif
